apiVersion: batch/v1
kind: Job
metadata:
  name: dns-demo
  labels:
    app: dns-demo
spec:
  completionMode: Indexed
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: dns-demo
    spec:
      subdomain: dns-demo-service
      restartPolicy: Never
      containers:
      - name: dns-demo
        image: busybox
        command:
        - sleep
        - "300"
---
apiVersion: v1
kind: Service
metadata:
  name: dns-demo-service
spec:
  selector:
    app: dns-demo
  ports:
  - name: http
    port: 80
